[package]
name = "easycomplete_rust_speed"
version = "0.1.0"
edition = "2021"

[lib]
path = "lua/easycomplete/lib/speed.rs"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.2", features = ["module", "luajit"] }
unicode-segmentation = "1.10"

