[package]
name = "easycomplete-util"
version = "0.1.0"
edition = "2024"

[lib]
path = "lua/easycomplete/rust/util.rs"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.2", features = ["module", "luajit"] }
